config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  get "users/profile" => "users#show"
  get "users/profile/edit" => "users#edit"
  get "users/account" => "users#show_account"
  get "rooms/own" => "rooms#own"

  resources :rooms
  resources :reservations
  resources :users

  post "/rooms/:id" => "reservations#create"
  patch "/rooms/:id", to: "reservations#create"

  root 'rooms#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :rooms
  has_many :reservations, dependent: :destroy
  has_one_attached :avatar

  before_create :default_avatar

  def default_avatar
    if !self.avatar.attached?
      self.avatar.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default-avatar.png')), filename: 'default-avatar.png', content_type: 'image/png')
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
   def after_sign_up_path_for(resource)
    users_profile_path
   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource)
    users_profile_path
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(params.require(:user).permit(:name, :profile, :avatar))
      flash[:notice] = "プロフィールを更新しました"
      redirect_to '/users/profile'
    else
      render "edit"
    end
  end

  def show_account
    @user = current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/header" %>

<article>
  <div class="side_menu">
    <%= link_to "アカウント", '/users/registrations/edit' %></p>
    <p>プロフィール</p>
  </div>

  <div class="container">
    <%= form_with model: @user do |f| %>
    <table class="table">
      <tr>
        <th scope="col"><%= f.label :avatar, "アバター" %></th>
        <td><%= f.file_field :avatar %></td>
      </tr>
      <tr>
        <th scope="col"><%= f.label :name, "ユーザー名" %></th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th scope="col"><%= f.label :profile, "プロフィール" %></th>
        <td><%= f.text_area :profile %></td>
      </tr>
    </table>
    <div>
      <ul>
        <%= f.submit "更新", class: "btn btn-outline-success" %><br>
        <%= link_to "キャンセル", '/users/profile', class: "btn btn-outline-secondary" %>
      </ul>
    </div>
    <% end %>
  </div> 
  </article>

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="container">
  <h3>プロフィール</h3>

  <article>
    <div class="side_menu">
      <%= link_to "アカウント", users_account_path %>
      <p>プロフィール</p>
    </div>
    <div class="account_container">
      <table class="table table-striped table-hover">
          <tr>
            <th scope="col">アバター</th>
            <td>
              <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar.variant(resize: "50x50>" ).processed %>
              <% else %>
              <%= image_tag "app/assets/images/default-avatar.png".variant(resize: "50x50>").processed %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th scope="col">ユーザー名</th>
            <td><%= @user.name %></td>
          </tr>
          <tr>
            <th scope="col">プロフィール</th>
            <td><%= @user.profile %></td>
          </tr>
      </table>
    </div>
  </article>
  <div>
    <ul>
      <a href="/users/profile/edit" class="btn btn-outline-secondary">編集</a>
    </ul>
  </div>
</div>

app/views/users/show_account.html.erb
<%= render "shared/header" %>

<div class="container">
  <h3>アカウント</h3>

  <article>
    <div class="side_menu">
      <p>アカウント</p>
      <%= link_to "プロフィール", users_profile_path %>
    </div>
    <div class="account_container">
      <table class="table table-striped table-hover">
        <tr>
          <th scope="col">メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th scope="col">パスワード</th>
          <td>*********</td>
        </tr>
      </table>
    </div>
  </article>
  <div>
    <ul>
      <a href="/users/edit" class="btn btn-outline-secondary">編集</a>
    </ul>
  </div>
</div>